site_name: Cyber Range Kyoushi Simulation

site_description: State machine based actor simulation framework for cyber range testbeds.
strict: true

theme:
  name: 'material'
#  custom_dir: 'docs/theme'

repo_name: kyoushi/simulation
repo_url: https://git-service.ait.ac.at/sct-cyberrange/tools/kyoushi/simulation

nav:
- Overview: index.md
- Code Reference:
    - Models: reference/model.md
    - States: reference/states.md
    - Transitions: reference/transitions.md
    - State Machine: reference/sm.md
    - Utility Functions: reference/util.md
    - Exceptions: reference/errors.md
- CLI Reference: cli.md
- Contributing: contributing.md
- License: license.md

markdown_extensions:
    - admonition
    - mkdocs-click
    - markdown_include.include
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.highlight
    - pymdownx.tabbed
    - pymdownx.tasklist
    - pymdownx.extra
    - toc:
        permalink: true



plugins:
- search
- exclude:
    glob:
    - _build/*
    - build/*
    - examples/*
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: true
    custom_templates: templates
    watch:
      - src/cr_kyoushi/simulation
