site_name: Cyber Range Kyoushi Simulation

site_description: State machine based actor simulation framework for cyber range testbeds.
strict: true

theme:
  name: 'material'
  logo: images/cr_icon.svg
  favicon: images/favicon.ico
  palette:
    scheme: ait

extra_css:
  - stylesheets/extra.css
  - stylesheets/jquery.fancybox.min.css

# Extra javascript
extra_javascript:
  - js/jquery-3.5.1.min.js
  - js/jquery.fancybox.min.js

repo_name: kyoushi/simulation
repo_url: https://git-service.ait.ac.at/sct-cyberrange/tools/kyoushi/simulation
# need to set manually since we use a private gitlab instance
edit_uri: edit/master/docs/

nav:
- Overview: index.md
- Usage:
    - Getting Started: usage/getting_started.md
    - Configuration: usage/configuration.md
    - Logging: usage/logging.md
    - CLI Reference: usage/cli.md
- Examples:
    - Traveler: examples/traveler.md
    - Decorated Traveler: examples/decorated_traveler.md
- Code Reference:
    - Models: reference/model.md
    - States: reference/states.md
    - Transitions: reference/transitions.md
    - State Machine: reference/sm.md
    - Utility Functions: reference/util.md
    - Exceptions: reference/errors.md
    - Configuration: reference/config.md
- Contributing: contributing.md
- License: license.md

markdown_extensions:
    - admonition
    - attr_list
    - mkdocs-click
    - markdown_include.include
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.tabbed
    - pymdownx.tasklist
    - pymdownx.extra
    - pymdownx.details
    - toc:
        permalink: true
        toc_depth: 3



plugins:
- search
- exclude:
    glob:
    - _build/*
    - build/*
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
            new_path_syntax: yes
            filters:
              - "!^_[^_]"
              - "!^__class__"
        rendering:
          show_source: true
    watch:
      - src/cr_kyoushi/simulation
      - README.md
      - CONTRIBUTING.md
- macros:
